# Generated by Django 6.0.2 on 2026-03-12 07:09

import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpTextModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', ckeditor.fields.RichTextField()),
                ('left_bg', models.ImageField(blank=True, null=True, upload_to='TmpText')),
                ('right_bg', models.ImageField(blank=True, null=True, upload_to='TmpText')),
            ],
        ),
    ]
