# Generated by Django 6.0.2 on 2026-03-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tmptextmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmptextmodel',
            name='left_bg',
            field=models.ImageField(blank=True, null=True, upload_to='TmpText/'),
        ),
        migrations.AlterField(
            model_name='tmptextmodel',
            name='right_bg',
            field=models.ImageField(blank=True, null=True, upload_to='TmpText/'),
        ),
    ]
