# Generated by Django 6.0.2 on 2026-03-12 08:40

import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_tmptextmodel_left_bg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTitleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
