# Generated by Django 6.0.2 on 2026-03-12 10:00

import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_sectiontitlemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAreaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img', ckeditor.fields.RichTextField()),
                ('img_1', models.URLField(blank=True, null=True)),
                ('img_2', models.URLField(blank=True, null=True)),
                ('img_3', models.URLField(blank=True, null=True)),
                ('img_4', models.URLField(blank=True, null=True)),
                ('img_5', models.URLField(blank=True, null=True)),
                ('img_6', models.URLField(blank=True, null=True)),
                ('img_7', models.URLField(blank=True, null=True)),
                ('img_8', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
