# Generated by Django 6.0.2 on 2026-03-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_companyareamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyareamodel',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to='TmpBanner'),
        ),
        migrations.AlterField(
            model_name='companyareamodel',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='TmpBanner'),
        ),
        migrations.AlterField(
            model_name='companyareamodel',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to='TmpBanner'),
        ),
        migrations.AlterField(
            model_name='companyareamodel',
            name='img_4',
            field=models.ImageField(blank=True, null=True, upload_to='TmpBanner'),
        ),
        migrations.AlterField(
            model_name='companyareamodel',
            name='img_5',
            field=models.ImageField(blank=True, null=True, upload_to='TmpBanner'),
        ),
        migrations.AlterField(
            model_name='companyareamodel',
            name='img_6',
            field=models.ImageField(blank=True, null=True, upload_to='TmpBanner'),
        ),
        migrations.AlterField(
            model_name='companyareamodel',
            name='img_7',
            field=models.ImageField(blank=True, null=True, upload_to='TmpBanner'),
        ),
        migrations.AlterField(
            model_name='companyareamodel',
            name='img_8',
            field=models.ImageField(blank=True, null=True, upload_to='TmpBanner'),
        ),
    ]
