# Generated by Django 6.0.2 on 2026-03-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_companyareamodel_img_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyareamodel',
            old_name='img',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='companyareamodel',
            name='img_1',
        ),
        migrations.RemoveField(
            model_name='companyareamodel',
            name='img_2',
        ),
        migrations.RemoveField(
            model_name='companyareamodel',
            name='img_3',
        ),
        migrations.RemoveField(
            model_name='companyareamodel',
            name='img_4',
        ),
        migrations.RemoveField(
            model_name='companyareamodel',
            name='img_5',
        ),
        migrations.RemoveField(
            model_name='companyareamodel',
            name='img_6',
        ),
        migrations.RemoveField(
            model_name='companyareamodel',
            name='img_7',
        ),
        migrations.RemoveField(
            model_name='companyareamodel',
            name='img_8',
        ),
        migrations.AddField(
            model_name='companyareamodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='CompanyArea/'),
        ),
        migrations.AddField(
            model_name='companyareamodel',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
