# Generated by Django 6.0.2 on 2026-03-18 07:24

import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_img_companyareamodel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TpmLatestServiceAreaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', ckeditor.fields.RichTextField()),
                ('title', ckeditor.fields.RichTextField()),
                ('dec', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='TpmLatestServiceArea/')),
            ],
        ),
    ]
