# Generated by Django 6.0.2 on 2026-03-18 09:35

import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_aboutmemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='TpmLatestServiceArea/')),
                ('tag', ckeditor.fields.RichTextField()),
                ('title', ckeditor.fields.RichTextField()),
                ('dec', ckeditor.fields.RichTextField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
