# Generated by Django 6.0.2 on 2026-03-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_businessmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='dec',
            field=models.URLField(blank=True, null=True),
        ),
    ]
