# Generated by Django 6.0.2 on 2026-03-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_businessmodel_dec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmodel',
            name='dec',
        ),
        migrations.RemoveField(
            model_name='businessmodel',
            name='link',
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Business/'),
        ),
    ]
