# Generated by Django 6.0.2 on 2026-03-18 10:49

import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_educationtitlemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', ckeditor.fields.RichTextField()),
                ('title', ckeditor.fields.RichTextField()),
                ('dec', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='educationtitlemodel',
            name='image',
        ),
    ]
