# Generated by Django 6.0.2 on 2026-03-18 11:11

import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_educationmodel_remove_educationtitlemodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', ckeditor.fields.RichTextField()),
                ('title', ckeditor.fields.RichTextField()),
                ('dec', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
