# Generated by Django 6.0.2 on 2026-03-18 11:45

import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_educationsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Business/')),
                ('tag', ckeditor.fields.RichTextField()),
                ('title', ckeditor.fields.RichTextField()),
                ('head', ckeditor.fields.RichTextField()),
                ('text', ckeditor.fields.RichTextField()),
                ('dec', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.DeleteModel(
            name='EducationsModel',
        ),
    ]
