# Generated by Django 6.0.2 on 2026-03-23 06:47

import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_experiencemodel_delete_educationsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTitleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', ckeditor.fields.RichTextField()),
                ('title', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
