# Generated by Django 6.0.2 on 2026-03-23 07:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_blogmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='dec',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
